### PR TITLE
tests for counting edges

### PR DESCRIPTION
**Pull request by Wikunia**
Before continuing with #53 I think it would be good to have these test cases. 
I assumed that the number is correct here just wanted to add a test such that we see when this changes. Not sure how to better test this.

### CODE REVIEW

**Comment by dkarrasch** [comment]
Awesome. Could you please rebase onto current master, so that the github action CI stuff runs on this PR.

You could try and see if something like `length(voronoiedges(tess))` works and is equal to the result of your loop. That should be an independent "stepping through" test. Could you please also fix the random seed in the "point can be in only one triangle" test. That test turned out to give spurious errors, probably when the test point was lying on some edge.

**Comment by dkarrasch** [comment]
With #53 we won't need the `collect` in the tests anymore, right?

**Comment by Wikunia** [comment]
Yes that might be true though I'm not 100% how iterators handle length :smile:

**Comment by Wikunia** [comment]
Seems like there is a difference in the delaunay edges between Julia 1.6 and 1.7 though? :confused:

**Comment by Wikunia** [comment]
Oh yeah that's true maybe have a file with a list of points that we can read and use those as our test case?

**Comment by dkarrasch** [comment]
We don't need a big test. Perhaps you could manually type a couple of points, say 5, at distinct locations, and then we know everything about that specific case. It is only important to step through the iterator, even if its length is short.

**Comment by Wikunia** [comment]
True, will do

**Comment by Wikunia** [comment]
Some lines have a length of zero though:
```
![image](https://user-images.githubusercontent.com/4931746/154293276-01975136-9475-4709-9dac-c6e762201ea0.png)
```
Here you can see the visible 12 voronoi edges.

**Comment by Wikunia** [comment]
> With #53 we won't need the `collect` in the tests anymore, right?

Actually we do because we don't provide the length of the iterator at the moment. We could walk through all and count and return that though if we want to.

**Pull request merged**
