### PR TITLE
v0.4 deprecations

### PR DESCRIPTION
**Pull request by swt30**
Removes some deprecation warnings that show up in julia v0.4. Adds a dependency on Compat.jl to keep compatibility with 0.3.

### CODE REVIEW

**Comment by skariel** [comment]
this needs some merging work, can you rebase? Otherwise I could do these changes manually

**Comment by swt30** [comment]
All done

**Comment by skariel** [comment]
Merged, thanks!

**Comment by swt30** [comment]
Worth tagging a new release as well?

**Comment by skariel** [comment]
yes, I don't remember now how it's done though... I can do it later when I have some time to re-learn this, or you can do this too if you want :)

**Comment by swt30** [comment]
I can't bump the version because it's done with a git tag. I think you just
need to make sure your local copy of the repository is up to date, then
start julia and do Pkg.tag("VoronoiDelaunay", :patch) followed by
Pkg.publish() and opening a pull request at the address given. This will
mark it as version 0.0.2 and then anyone else using the package will get
the latest copy :)

**Comment by roames** [comment]
Hi there @skariel if you find the time it would probably be a good idea to follow @swt30's suggestion here and bump the version upstream.

**Pull request merged**
